name: pharma_scan
description: "Assistant pharmacien offline : scan Data Matrix, identification Princeps/Génériques et alertes stock via la base BDPM."
# The following line prevents the package from being accidentally published to
# pub.dev using `dart pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ^3.38.3

platforms:
  android:

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `dart pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `dart pub outdated`.
dependencies:
  archive: ^4.0.0
  auto_route: ^11.0.0
  characters: ^1.4.0
  collection: ^1.19.1
  dart_either: ^2.0.0
  dart_mappable: ^4.6.1
  decimal: ^3.2.4
  diacritic: ^0.1.3
  dio: ^5.9.0
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  gap: ^3.0.1
  hooks_riverpod: ^3.0.3
  image_picker: ^1.2.1
  meta: ^1.15.0
  mobile_scanner: ^7.1.3
  package_info_plus: ^9.0.0
  path: ^1.9.0
  petitparser: ^7.0.0
  path_provider: ^2.1.5
  quick_actions: ^1.1.0
  riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  signals_flutter: ^6.3.0
  scrollable_positioned_list: ^0.3.8
  shadcn_ui: ^0.42.0
  sqlite3: ^2.9.4
  sqlite3_flutter_libs: ^0.5.40
  talker: ^5.1.0
  talker_flutter: ^5.1.0
  talker_riverpod_logger: ^5.1.0
  url_launcher: ^6.3.2
  talker_dio_logger: ^5.1.7

dev_dependencies:
  auto_route_generator: ^10.3.0
  build_runner: ^2.10.4
  custom_lint: ^0.8.1
  dart_mappable_builder: ^4.6.1
  dependency_validator: ^5.0.3
  drift_dev: ^2.30.0
  flutter_launcher_icons: ^0.14.4
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  patrol: ^4.0.1
  pharma_lints:
    path: tool/custom_lints/pharma_lints
  riverpod_generator: ^3.0.3
  sort_pubspec_dependencies: ^0.0.2
  test: ^1.26.2
  very_good_analysis: ^10.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/test_images/
    - assets/database/reference.db.gz

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_launcher_icons:
  android: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 24
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/icon/icon.png"
  android_12:
    image: "assets/icon/icon.png"
    color: "#FFFFFF"

# Patrol configuration for E2E testing
patrol:
  app_name: PharmaScan
  android:
    package_name: com.pharmascan.app
  ios:
    bundle_id: com.pharmascan.app
