name: pharma_lints
description: Custom lint rules for PharmaScan
version: 1.0.0

environment:
  sdk: ^3.4.0

dependencies:
  analyzer: ^8.4.0
  custom_lint_builder: ^0.8.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0