name: Build Pharma DB

on:
  schedule:
    - cron: "0 4 * * *" # 4 AM Paris Time
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1

      - name: Install
        run: cd backend_pipeline && bun install

      - name: Build DB
        run: cd backend_pipeline && bun run src/index.ts

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: reference-db
          path: backend_pipeline/reference.db
